"""Endpoints for reading real training/evaluation metrics from outputs."""
import csv
import json
import subprocess
import sys
import threading
import time
from pathlib import Path
from fastapi import APIRouter, HTTPException, Query

router = APIRouter()

METRICS_DIR = Path("outputs/metrics")
LOGS_DIR = Path("outputs/logs")

EVALUATIONS = {
    "detection": {
        "label": "Detection ISIC",
        "total": 390,
        "args": ["--model", "detection", "--config", "configs/detection_config.yaml", "--checkpoint", "outputs/checkpoints/best_detection.pth", "--split", "test", "--output-csv", "outputs/metrics/isic2018_detection_test_per_image.csv"],
    },
    "isic-segmentation": {
        "label": "Phân đoạn ISIC",
        "total": 390,
        "args": ["--model", "segmentation", "--config", "configs/segmentation_config.yaml", "--checkpoint", "outputs/checkpoints/best_segmentation.pth", "--split", "test", "--output-csv", "outputs/metrics/isic2018_test_per_image.csv"],
    },
    "chest-xray-segmentation": {
        "label": "Phân đoạn X-ray",
        "total": 22,
        "args": ["--model", "segmentation", "--config", "configs/chest_xray_segmentation_config.yaml", "--checkpoint", "outputs/checkpoints/best_chest_xray_segmentation.pth", "--split", "test", "--output-csv", "outputs/metrics/chest_xray_test_per_image.csv"],
    },
    "isic-pipeline": {
        "label": "Full pipeline ISIC",
        "total": 390,
        "script": "scripts/evaluate_pipeline.py",
        "args": ["--split", "test", "--output-csv", "outputs/metrics/isic2018_pipeline_test_per_image.csv"],
    },
    "isic-unet-all": {
        "label": "U-Net diagnostic toàn bộ ISIC",
        "total": 2594,
        "args": ["--model", "segmentation", "--config", "configs/segmentation_unet_baseline_config.yaml", "--checkpoint", "outputs/checkpoints/best_segmentation_unet_baseline.pth", "--split", "all", "--output-csv", "outputs/metrics/isic2018_unet_baseline_all_2594_per_image.csv"],
    },
}
_evaluation_lock = threading.Lock()
_evaluation_state = {"running": False, "kind": None, "message": "", "started_at": None}


def _run_evaluation(kind: str, limit: int):
    spec = EVALUATIONS[kind]
    command = [sys.executable, spec.get("script", "scripts/evaluate.py"), *spec["args"], "--max-images", str(limit)]
    try:
        result = subprocess.run(command, capture_output=True, text=True, cwd=Path.cwd())
        message = result.stdout.strip() if result.returncode == 0 else (result.stderr.strip() or result.stdout.strip())
        with _evaluation_lock:
            _evaluation_state.update(running=False, success=result.returncode == 0, message=message, finished_at=int(time.time() * 1000))
    except Exception as exc:
        with _evaluation_lock:
            _evaluation_state.update(running=False, success=False, message=str(exc), finished_at=int(time.time() * 1000))


def _read_json(path: Path):
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
    # Allow the UI to distinguish evaluation runs with identical metric values.
    data["updated_at"] = path.stat().st_mtime_ns // 1_000_000
    return data


def _read_history(path: Path):
    if not path.exists():
        return None
    with open(path, newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    return {
        "path": str(path),
        "epochs": len(rows),
        "last": rows[-1] if rows else None,
        "rows": rows,
    }


@router.get("/metrics")
async def metrics():
    """Return metrics generated by scripts/evaluate.py and training history CSVs."""
    return {
        "summaries": {
            "chest_xray_segmentation": _read_json(
                METRICS_DIR / "chest_xray_test_per_image.summary.json"
            ),
            "isic2018_segmentation": _read_json(
                METRICS_DIR / "isic2018_test_per_image.summary.json"
            ),
            "isic2018_detection": _read_json(
                METRICS_DIR / "isic2018_detection_test_per_image.summary.json"
            ),
            "isic2018_pipeline": _read_json(
                METRICS_DIR / "isic2018_pipeline_test_per_image.summary.json"
            ),
            "isic2018_unet_baseline": _read_json(
                METRICS_DIR / "isic2018_unet_baseline_test_per_image.summary.json"
            ),
            "isic2018_unet_all_diagnostic": _read_json(
                METRICS_DIR / "isic2018_unet_baseline_all_2594_per_image.summary.json"
            ),
        },
        "training_history": {
            "detection": _read_history(
                LOGS_DIR / "best_detection_training_history.csv"
            ),
            "isic2018_segmentation": _read_history(
                LOGS_DIR / "best_segmentation_training_history.csv"
            ),
            "chest_xray_segmentation": _read_history(
                LOGS_DIR / "best_chest_xray_segmentation_training_history.csv"
            ),
        },
    }


@router.get("/metrics/evaluation-status")
async def evaluation_status():
    with _evaluation_lock:
        return {**_evaluation_state, "options": {
            key: {"label": value["label"], "total": value["total"]}
            for key, value in EVALUATIONS.items()
        }}


@router.post("/metrics/evaluate/{kind}", status_code=202)
async def start_evaluation(kind: str, limit: int | None = Query(default=None, ge=1)):
    if kind not in EVALUATIONS:
        raise HTTPException(status_code=404, detail="Loại đánh giá không hợp lệ")
    spec = EVALUATIONS[kind]
    image_limit = spec["total"] if limit is None else min(limit, spec["total"])
    with _evaluation_lock:
        if _evaluation_state["running"]:
            raise HTTPException(status_code=409, detail="Một lượt đánh giá khác đang chạy")
        _evaluation_state.update(
            running=True,
            kind=kind,
            label=spec["label"],
            limit=image_limit,
            success=None,
            message="",
            started_at=int(time.time() * 1000),
            finished_at=None,
        )
    threading.Thread(target=_run_evaluation, args=(kind, image_limit), daemon=True).start()
    return {**_evaluation_state}
